### ISSUE TITLE
Issue in filter change

### ISSUE THREAD

**Issue by Fernandobo21** [victorsolaya/Multiselect_Records_PCF#19]
Hi again.

First of all, thanks for the last fix a release of the PCF.

I detected a issue when the filter change and it has selected items. 
For example if i filter by letter "A" and select any records, then open again the search field and filter by "Z".
After selecting the records for the new search, it's not keeping the first selected registries.

This is the step-by-step:

1. Filter in the search field. For example filter by letters "AC".
2. Select as many records you want.
3. Change the filter to a complete new search. For example "RE". At this point you will see that the selected records dissapear.
4. Select as many record you want again.

Don't hesitate to ask me anything you need.
Thanks in advance.

**Comment by victorsolaya** [comment]
Hi @Fernandobo21 

This has been fixed in release 1.0.0.7.
Could you try and let me know please?

Thank you

**Comment by Fernandobo21** [comment]
Hi again.
Again thanks for the last release.
I found one minor bug, after s
One of the colums stay blank with the last release

I will keep this issue opened if yuo don't mind.
Thanks agains for giving me feedback.

**Comment by victorsolaya** [comment]
Hi @Fernandobo21 
I have performed some new improvements with the issue you had. Those columns now appear, that was because I was selecting only the id and the data. Apart from that, I have performed an improvement to the filter, so now you can bound not only to a SingleLine.Text, but a SingleLine.Multiple and Multiple so you can bound them.

Hopefully this release is what you expect. Many thanks!

**Comment by Fernandobo21** [comment]
Everything fixed and working perfect.
Thanks again for the fix
