### ISSUE TITLE
Publisher changed will not import

### ISSUE THREAD

**Issue by acehaddock** [victorsolaya/Multiselect_Records_PCF#23]
we were looking to import the updated 1.0.0.8 solution into our env and we got an error
the follow managed solution can be imported: multiselect record-solution. the publisher name cannot be changed from VictorSanchez to victorsanchez. 

I can edit the solution file but not something I would want to do moving forward.  I looked over release notes and did not see where this was changed.  was this an oversite on a change of Publisher?

**Comment by victorsolaya** [comment]
Hi!
Yes, this is because the editor was changed to lowercase version due to some problems when created with camelcase.

The reason of this change was because when I tried to import with VictorSanchez it failed for some reason and it didnt allow me to import until I deleted the managed solution and reimport it again with the new editor name.

I would suggest to edit the name of the editor and then try to import this new update.
The name wont be changed ever again, it will always be victorsanchez from now on in the case a new update is released.

Sorry for that inconvenience. Let me know if that helped.

Thank you!

Victor
________________________________
From: acehaddock ***@***.***>
Sent: Tuesday, April 13, 2021 2:59:32 PM
To: victorsolaya/Multiselect_Records_PCF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [victorsolaya/Multiselect_Records_PCF] Publisher changed will not import (#23)


we were looking to import the updated 1.0.0.8 solution into our env and we got an error
the follow managed solution can be imported: multiselect record-solution. the publisher name cannot be changed from VictorSanchez to victorsanchez.

I can edit the solution file but not something I would want to do moving forward. I looked over release notes and did not see where this was changed. was this an oversite on a change of Publisher?

**Comment by victorsolaya** [comment]
Hi @acehaddock Could you finally solve the issue with the info provided above?

Thank you

**Comment by acehaddock** [comment]
@victorsolaya   i was able to edit it but i will have to edit it every time now as i cant export it then reimport it.  but its working now just need to note i have to do it on every update
