### ISSUE TITLE
When I compile, it doesn't works in power apps

### ISSUE THREAD

**Issue by TheDarktor** [victorsolaya/Multiselect_Records_PCF#30]
I cannot import the solution when i compile, i don't know why but i think it is missing some files.

I receive this error: 
![image](https://user-images.githubusercontent.com/55066829/121945085-c2c55e80-cd29-11eb-8fa2-fef37bf2164a.png)
"Failed to import solution: PSA_MultiselectRecordsEntity".

And this is the log file:
[PSA_MultiselectRecordsEntity_import.zip](https://github.com/victorsolaya/Multiselect_Records_PCF/files/6650643/PSA_MultiselectRecordsEntity_import.zip)

Do you have any idea about what is wrong?

**Comment by victorsolaya** [comment]
Hi @TheDarktor  that is because your web resource is too big
You have two options for doing this.
1. Reducing the size doing a **msbuild /p:Configuration=Release**
2. Increase the amount of mb:

![image](https://user-images.githubusercontent.com/11043789/121959558-40f32680-cd65-11eb-8ce3-805b7b673a02.png)
![image](https://user-images.githubusercontent.com/11043789/121959578-46507100-cd65-11eb-836f-eaba2aec8294.png)
![image](https://user-images.githubusercontent.com/11043789/121959598-4b152500-cd65-11eb-835b-e16db017567e.png)
![image](https://user-images.githubusercontent.com/11043789/121959625-523c3300-cd65-11eb-9978-910a4112bf77.png)

**Comment by TheDarktor** [comment]
Thank you very much for your quick answer, i followed the second step and now it's working perfectly. I really like your work, and your documentation is so good.
