### ISSUE TITLE
the control remain active while the record is in "inactive" Status

### ISSUE THREAD

**Issue by malkhawaja** [victorsolaya/Multiselect_Records_PCF#34]
Hi,
when I convert a record to the "Inactive" Status, all fields become un-editable on the form except your control, and I am still able to add and remove data from the field.

I think it should become inactive and block editing if the recored is inactive.

thanks.

**Comment by victorsolaya** [comment]
Hi! @malkhawaja The issue has been fixed with latest version. Let me know how it goes, 
![image](https://user-images.githubusercontent.com/11043789/145275239-19e391ee-0ca1-46a5-bd40-c2233d37a5db.png)

I have added the removal of the X next to each tag as well, as it didn't have any sense as well apart from the search text field.

Many thanks for the feedback!

**Comment by malkhawaja** [comment]
it is working like a charm... thanks for the quick response!
