### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vernetmatias** [victorsolaya/Multiselect_Records_PCF#36]
Hello Victor,
I implemented your control but there is something not rigth.

I can´t select multiple elements. I putt the option IsMultiple with true and left it blank, but nothing still select only one record...and the name i get its with that format...

![image](https://user-images.githubusercontent.com/36961292/167883096-1887ae6f-d77c-4b04-80e9-02f502f5b966.png)

![image](https://user-images.githubusercontent.com/36961292/167884787-e0f90f4f-597b-4471-84bf-f36dece530b3.png)

**Comment by victorsolaya** [comment]
Hey! 

I believe your problem is in the main attribute id. It should be axx_tipodeobjetivoid, you put axx_tipodeobjetivoId, (Uppercase I in the Id)
Let me know if that solves the problem.
The final objective of the JSON is to have the ID and the Name to show, both of them, so it seems the problem you are having is coming from there

**Comment by vernetmatias** [comment]
Hello Victor, you were right!, thanks

Can I add a few ideas?,It would be great if the records when selected
associate them with the parent record too. Attach them to a subrid that
could be hidden.

and also the names of the records pasted on the field could only be the
name?

instead of
this: [{"id":"185da078-d6e1-e811-a974-000d3ac1b7b6","name":"Prueba
1"},{"id":"c6ff430e-ece1-e811-a974-000d3ac1b7b6","name":"Potencial
productor producto Pyme"}]

this: Prueba 1, Potencial productor producto Pyme
[image: image.png]

thanks!
