### ISSUE TITLE
No values showing

### ISSUE THREAD

**Issue by NataliWinOn365** [victorsolaya/Multiselect_Records_PCF#45]
I am trying to set up the control as follows: 
![2023-06-09_14-55-10](https://github.com/victorsolaya/Multiselect_Records_PCF/assets/79563854/a249824a-18b9-41f9-87b7-4effe5181760)
![2023-06-09_14-57-09](https://github.com/victorsolaya/Multiselect_Records_PCF/assets/79563854/23cd09b3-65a8-4441-b1fd-851a503ce59c)

I get the following erorr: 
![Error](https://github.com/victorsolaya/Multiselect_Records_PCF/assets/79563854/67c8c0cc-37fe-4c7d-9f33-f42c53971f89)
Thanks in advance for the guidance. I am looking forward to using this great control!

**Comment by victorsolaya** [comment]
Hello @NataliWinOn365  it seems it is because the filter parameter.
You need to put something like it is said in the docs:
https://github.com/victorsolaya/Multiselect_Records_PCF#example-with-one-parameter

?$filter=contains(fullname, '{0}')

The number 0 means what you are setting in the field

Hopefully that helps
